baseURL: "https://flourishing-brioche-c26997.netlify.app"
languageCode: "de-DE"
title: HanovaTech
params:
  slogan: Digitale Lösungen für Ihr Unternehmen
  description: Der Dienstleister für IT-Consulting, Managed Services, Software Solutions und Cybersecurity in Hannover. Ihr Partner für die Digitalisierung Ihres Unternehmens!

markup:
  goldmark:
    renderer:
      unsafe: true
