baseURL: "https://hanovatech.de"
languageCode: "de-DE"
title: HanovaTech

params:
  facebook_pixel_id: 445883344440518
  google_tag_key: G-FLN8S6BVPV
  google_maps_key: AIzaSyBdanO51ibHQTi0fFcyug3upt2I3SqCVVI
  google_maps_query: HanovaTech

disableKinds:
  - taxonomy
  - term

markup:
  goldmark:
    renderer:
      unsafe: true
