backend:
  name: git-gateway
  branch: main
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: pages
    label: Pages
    files:
      - name: home
        label: Home
        file: "/content/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - label: Hero Section
            name: heroSection
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
          - label: Services Section
            name: servicesSection
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - label: Services
                name: services
                widget: list
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Description", name: "description", widget: "string" }
                  - { label: "Icon", name: "icon", widget: "string" }
              - label: Carousel
                name: carousel
                widget: list
                fields:
                  - { label: "Image", name: "image", widget: "image" }
          - label: Team Section
            name: teamSection
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string" }
              - { label: "Description", name: "description", widget: "string" }
              - label: Team
                name: members
                widget: list
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Role", name: "role", widget: "string" }
                  - { label: "Specialty", name: "specialty", widget: "string" }
                  - { label: "Image", name: "image", widget: "image" }
      - name: references
        label: Referenzen
        file: "/content/references.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: about
        label: Über uns
        file: "/content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: career
        label: Karriere
        file: "/content/career.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: partners
        label: Partner
        file: "/content/partners.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
      - name: contact
        label: Kontakt
        file: "/content/contact/_index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "string", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
  - name: services
    label: Services
    folder: /content/services
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: blog
    label: Blog
    folder: /content/blog
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime", required: false }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    files:
      - name: navigation
        label: Navigation
        file: /data/navigation.yaml
        fields:
          - label: Main
            name: main
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
              - { label: "Icon List", name: "iconList", widget: "boolean" }
              - label: Sublinks
                name: childs
                widget: list
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Link", name: "url", widget: "string" }
                  - { label: "Icon", name: "icon", widget: "string" }
                  - { label: "Description", name: "description", widget: "string" }
          - label: Footer
            name: footer
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - label: Links
                name: childs
                widget: list
                fields:
                  - { label: "Name", name: "name", widget: "string" }
                  - { label: "Link", name: "url", widget: "string" }
      - name: google
        label: Google
        file: /data/google.yaml
        fields:
          - { label: "Google Tag", name: "google_tag_key", widget: "string" }
          - { label: "Google Maps Key", name: "google_maps_key", widget: "string" }
          - { label: "Google Maps Query", name: "google_maps_query", widget: "string" }
